language: scala
scala:
  - 2.12.1

sudo: false

script:
  - sbt clean coverage test coverageReport &&
    sbt coverageAggregate
after_success:
  - sbt coveralls

notifications:
   email:
    recipients:
       - parsentev@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always